import os
from flask import Flask, render_template, request, redirect, url_for, session

app = Flask(__name__)
app.secret_key = os.getenv('APP_SECRET_KEY', 'dev-secret-key')

@app.route('/')
def home():
    app_info = session.get('app_info', {
        'name': 'Simple Py Webapp',
        'version': '1.0.0',
        'description': 'A basic Flask web application demonstrating simple web page rendering.',
        'author': 'Generated by GitHub Copilot'
    })
    return render_template('index.html', app_info=app_info)

@app.route('/update', methods=['POST'])
def update():
    app_name = request.form.get('app_name', 'Simple Py Webapp')
    description = request.form.get('description', 'A basic Flask web application demonstrating simple web page rendering.')
    person_name = request.form.get('person_name', '')
    author = f'Generated by GitHub Copilot ({person_name})' if person_name else 'Generated by GitHub Copilot'
    session['app_info'] = {
        'name': app_name,
        'version': '1.0.0',
        'description': description,
        'author': author
    }
    return redirect(url_for('home'))

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)