import pytest
from app import app

@pytest.fixture
def client():
    app.config['TESTING'] = True
    with app.test_client() as client:
        yield client

def test_home_page(client):
    response = client.get('/')
    assert response.status_code == 200
    assert b'Welcome to Simple Py Webapp' in response.data

def test_update_page_post(client):
    response = client.post('/update', data={
        'app_name': 'Test App',
        'description': 'Test Description',
        'person_name': 'Test User'
    }, follow_redirects=True)
    assert response.status_code == 200
    assert b'Welcome to Test App' in response.data
    assert b'Test Description' in response.data
    assert b'Generated by GitHub Copilot (Test User)' in response.data

def test_update_without_person_name(client):
    response = client.post('/update', data={
        'app_name': 'Test App 2',
        'description': 'Test Description 2',
        'person_name': ''
    }, follow_redirects=True)
    assert response.status_code == 200
    assert b'Generated by GitHub Copilot' in response.data
    assert b'(Test User)' not in response.data

def test_form_rendering(client):
    response = client.get('/')
    assert b'Update this Page' in response.data
    assert b'<form' in response.data

def test_session_persistence(client):
    # Update and check if session persists
    client.post('/update', data={
        'app_name': 'Persistent App',
        'description': 'Persistent Desc',
        'person_name': 'Persistent User'
    })
    response = client.get('/')
    assert b'Welcome to Persistent App' in response.data